Fix undefined locsl variable "path" in Magic#load.
This fixes the following:

  irb(main):001:0> require 'ffi-magic'
  => true
  irb(main):002:0> magic = Magic.new
  => #<Magic:0x007fea14143678 @flags=0, @path=nil, @cookie=#<FFI::Pointer address=0x007fea1358f7d0>>
  irb(main):003:0> magic.load
  NameError: undefined local variable or method `path' for #<Magic:0x007fea14143678>

Plus adds two new attribute readers: "flags" and "path" for convenience.

Signed-off-by: Krzysztof Wilczynski <krzysztof.wilczynski@linux.com>